const state = { settings: {}, gallery: [], leads: [] };
let toastTimer;
const API_BASE = String(window.STUDIO_API_BASE || '').replace(/\/$/, '');
const apiUrl = (path) => `${API_BASE}${path}`;

const byId = (id) => document.getElementById(id);
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const formatDate = (value) => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value}T12:00:00`)) : 'Date not set';

async function api(path, options = {}) {
  const response = await fetch(apiUrl(path), { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  if (response.status === 401) { document.body.classList.remove('is-authenticated'); throw new Error('Authentication required'); }
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'Request failed'); }
  return response.status === 204 ? null : response.json();
}
function toast(message) { const el = byId('adminToast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 2200); }
function showLoginError(message = '') { byId('loginError').textContent = message; }

function renderStats() { byId('leadCount').textContent = state.leads.length; byId('navLeadCount').textContent = state.leads.length; byId('galleryCount').textContent = state.gallery.length; byId('viewCount').textContent = 'Live'; byId('phoneStat').textContent = (state.settings.phone || '').replace('+91', '').trim(); }
function renderRecentLeads() { const target = byId('recentLeads'); const recent = state.leads.slice().reverse().slice(0, 4); target.innerHTML = recent.length ? recent.map((lead) => `<div class="lead-row"><div><strong>${escapeHtml(lead.name || 'Unnamed enquiry')}</strong><small>${escapeHtml(lead.eventType || 'Event')} · ${escapeHtml(lead.service || 'Service')}</small></div><span class="lead-date">${escapeHtml(formatDate(lead.date))}</span></div>`).join('') : '<div class="empty-state">No enquiries yet. Your next date request will appear here.</div>'; }
function renderLeadTable() { const target = byId('leadTable'); const recent = state.leads.slice().reverse(); target.innerHTML = recent.length ? recent.map((lead, index) => `<tr><td><strong>${escapeHtml(lead.name || 'Unnamed')}</strong><small>${escapeHtml(lead.phone || '')}</small></td><td>${escapeHtml(lead.eventType || '-')}</td><td>${escapeHtml(formatDate(lead.date))}</td><td>${escapeHtml(lead.location || '-')}</td><td>${escapeHtml(lead.service || '-')}</td><td>${escapeHtml(new Date(lead.createdAt || Date.now()).toLocaleDateString('en-IN'))}</td><td><button class="delete-button" type="button" data-delete-lead="${state.leads.length - 1 - index}">Delete</button></td></tr>`).join('') : '<tr><td colspan="7"><div class="empty-state">No enquiries yet.</div></td></tr>'; target.querySelectorAll('[data-delete-lead]').forEach((button) => button.addEventListener('click', async () => { try { await api(`/api/leads/${button.dataset.deleteLead}`, { method: 'DELETE' }); await refresh(); toast('Enquiry removed'); } catch (error) { toast(error.message); } })); }
function renderGallery() { const target = byId('adminGallery'); target.innerHTML = state.gallery.length ? state.gallery.map((item) => `<article class="gallery-admin-item"><img src="${escapeHtml(item.url)}" alt="${escapeHtml(item.title)}" /><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.category)}</small><button class="delete-button" type="button" data-delete-gallery="${escapeHtml(item.id)}">Remove</button></div></article>`).join('') : '<div class="empty-state">No gallery images yet.</div>'; target.querySelectorAll('[data-delete-gallery]').forEach((button) => button.addEventListener('click', async () => { try { await api(`/api/gallery/${encodeURIComponent(button.dataset.deleteGallery)}`, { method: 'DELETE' }); await refresh(); toast('Gallery image removed'); } catch (error) { toast(error.message); } })); }
function loadSettings() { Object.entries(state.settings).forEach(([key, value]) => { const field = document.querySelector(`[name="${key}"]`); if (field) field.value = value; }); }
async function refresh() { const [settings, gallery, leads] = await Promise.all([api('/api/settings'), api('/api/gallery'), api('/api/leads')]); state.settings = settings; state.gallery = gallery; state.leads = leads; renderStats(); renderRecentLeads(); renderLeadTable(); renderGallery(); loadSettings(); }

function setupNavigation() { const links = document.querySelectorAll('.nav-link'); const panels = document.querySelectorAll('.admin-section'); function show(name) { panels.forEach((panel) => panel.classList.toggle('active-section', panel.dataset.panel === name)); links.forEach((link) => link.classList.toggle('active', link.dataset.section === name)); history.replaceState(null, '', `#${name}`); window.scrollTo({ top: 0, behavior: 'smooth' }); } links.forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); show(link.dataset.section); })); document.querySelectorAll('[data-jump]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); show(link.dataset.jump); })); const initial = window.location.hash.slice(1); show(['overview', 'enquiries', 'gallery-manager', 'settings'].includes(initial) ? initial : 'overview'); }
async function boot() { try { const session = await api('/api/session'); if (!session.authenticated) return; document.body.classList.add('is-authenticated'); await refresh(); setupNavigation(); } catch (error) { if (error.message !== 'Authentication required') showLoginError('Server se connection nahi ho paaya.'); } }

byId('loginForm').addEventListener('submit', async (event) => { event.preventDefault(); showLoginError(''); const body = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/api/login', { method: 'POST', body: JSON.stringify(body) }); document.body.classList.add('is-authenticated'); await refresh(); setupNavigation(); } catch (error) { showLoginError(error.message === 'Invalid username or password' ? 'Username ya password galat hai.' : error.message); } });
byId('logoutButton').addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); document.body.classList.remove('is-authenticated'); window.location.hash = ''; showLoginError(''); });
async function readImageData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function uploadLocalImage(file) { const uploaded = await api('/api/upload', { method: 'POST', body: JSON.stringify({ data: await readImageData(file) }) }); return uploaded.url; }
const galleryFileInput = document.querySelector('#galleryFile');
const galleryFileStatus = document.querySelector('#galleryFileStatus');
galleryFileInput.addEventListener('change', () => { const file = galleryFileInput.files[0]; galleryFileStatus.textContent = file ? `${file.name} selected` : 'No photo selected'; });
byId('galleryForm').addEventListener('submit', async (event) => { event.preventDefault(); try { const form = event.currentTarget; const file = galleryFileInput.files && galleryFileInput.files[0]; if (!file || !file.size) throw new Error('Choose image from computer par photo select karein'); const data = new FormData(form); const response = await fetch(apiUrl('/api/gallery-upload'), { method: 'POST', body: data, credentials: 'include' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Upload failed'); form.reset(); galleryFileStatus.textContent = 'No photo selected'; await refresh(); toast('Image added to gallery'); } catch (error) { toast(error.message); } });
byId('settingsForm').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/api/settings', { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); byId('settingsStatus').textContent = 'Saved just now'; byId('lastUpdated').textContent = `Updated ${new Date().toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}`; await refresh(); toast('Business details saved'); } catch (error) { toast(error.message); } });
byId('clearLeads').addEventListener('click', async () => { if (!state.leads.length || window.confirm('Clear all saved enquiries?')) { try { await api('/api/leads', { method: 'DELETE' }); await refresh(); toast('Enquiries cleared'); } catch (error) { toast(error.message); } } });
boot();
